### ISSUE TITLE
第一次裁剪跟之后的裁剪

### ISSUE THREAD

**Issue by zongmi** [teojs/clipic#3]
`clipic.getImage({
				width: 900,
				height: 638,
				src: a.target.result,
				onDone: function (e) {

第一次裁剪后图片的宽高，跟之后裁剪的宽高不一致。

第一次按设置的宽高900x638，
第二次就变了 根据客户端分辨率 变成260x192之类的
}`

**Comment by teojs** [comment]
> `clipic.getImage({
> width: 900,
> height: 638,
> src: a.target.result,
> onDone: function (e) {
> 
> 第一次裁剪后图片的宽高，跟之后裁剪的宽高不一致。
> 
> 第一次按设置的宽高900x638，
> 第二次就变了 根据客户端分辨率 变成260x192之类的
> }`

不是很懂你的描述，意思是设置了900x638，裁剪出来的是260x192？如果设置了width跟height，请不要设置ratio，否则以ratio为主。

**Comment by zongmi** [comment]
谢谢作者大大回复
没有设置ratio
页面不刷新的情况下除了第一张设置的宽高生效，之后再上传就失效了
第一张上传就是900x638 第二张就根据客户端分辨率自动设置图片裁剪后的宽高了

**Comment by teojs** [comment]
@zongmi 确实有这个问题，将会很快修复，感谢反馈跟支持🤭
