### ISSUE TITLE
手机应用双开，双开的应用无法正常打开图片

### ISSUE THREAD

**Issue by zongmi** [teojs/clipic#4]
应用：双开微信
操作步骤：上传图片->打开相册->选择图片->无弹出无反应

**Comment by teojs** [comment]
你好，能提供系统版本跟微信版本吗？

**Comment by teojs** [comment]
最好能贴一下代码截图

**Comment by zongmi** [comment]
### 测试手机：

1. > 小米5  双开微信版本：7.0.3
![504922159039344213](https://user-images.githubusercontent.com/18360503/63561822-d9ffee80-c58d-11e9-826e-438661dfdcda.jpg)

2. > 华为 mate 20 Pro   微信版本：7.0.6
![901862755782827336](https://user-images.githubusercontent.com/18360503/63561693-74abfd80-c58d-11e9-9edc-ae13b26a6bfd.jpg)
我是先发现我这里双开的微信不能正常上传，
然后就在双开的微信打开 https://teojs.github.io/clipic/ 测试发现也不行

**Comment by teojs** [comment]
@zongmi 这似乎是微信分身的问题，在微信分身的环境下，<input type="file> 的onchange事件无效，所以跟插件无关，在网上能搜到相关问题，但目前似乎没有解决方案，这是在网上搜到的一条相关问题https://segmentfault.com/q/1010000017365988

**Comment by zongmi** [comment]
这样啊，感谢作者大大解惑
